[package]
name = "rust-paint"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"
winit_input_helper = "0.14"
pixels = "0.12"
log = "0.4"
env_logger = "0.10"
error-iter = "0.4"

[dev-dependencies]
